language: node_js
node_js:
- '4.1'
- '0.12'
before_script:
- npm install -g grunt-cli coveralls
script:
- npm run test
- grunt jshint
sudo: false
branches:
  only:
  - master
after_success:
  - npm run coverage
  - coveralls
cache:
  directories:
  - node_modules